const faker = require("faker");

module.exports = () => {
  const data = { users: [] };

  const userIds = [];
  const weekdays = [
    "sunday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
  ];
  const subjects = [
    "Music",
    "Accompanying",
    "Chamber music",
    "Church music",
    "Conducting",
    "Choral conducting",
    "Orchestral conducting",
    "Wind ensemble conducting",
    "Early music",
    "Jazz studies",
    "Musical composition",
    "Music education",
    "Music history",
    "Musicology",
    "Historical musicology",
    "Systematic musicology",
    "Ethnomusicology",
    "Music theory",
    "Orchestral studies",
    "Organology",
    "Organ and historical keyboards",
    "Piano",
    "Strings, harp, oud, and guitar",
    "Singing",
    "Woodwinds, brass, and percussion",
    "Recording",
    "Dance",
    "Choreography",
    "Dance notation",
    "Ethnochoreology",
    "History of dance",
    "Television",
    "Television studies",
    "Theatre",
    "Acting",
    "Directing",
    "Dramaturgy",
    "History",
    "Musical theatre",
    "Playwrighting",
    "Puppetry",
    "Scenography",
    "Stage design",
    "Ventriloquism",
    "Film",
    "Animation",
    "Film criticism",
    "Filmmaking",
    "Film theory",
    "Live action",
    "Visual arts",
    "Fine arts",
    "Graphic arts",
    "Drawing",
    "Painting",
    "Photography",
    "Sculpture",
    "Applied arts",
    "Animation",
    "Calligraphy",
    "Decorative arts",
    "Mixed media",
    "Printmaking",
    "Studio art",
    "Architecture",
    "Interior architecture",
    "Landscape architecture",
    "Landscape design",
    "Landscape planning",
    "Architectural analytics",
    "Historic preservation",
    "Interior design",
    "Technical drawing",
    "Fashion",
    "African history",
    "American history",
    "Ancient history",
    "Ancient Egypt",
    "Carthage",
    "Ancient Greek history",
    "Ancient Roman history",
    "Assyrian Civilization",
    "Bronze Age Civilizations",
    "Biblical history",
    "History of the Indus Valley Civilization",
    "Preclassic Maya",
    "History of Mesopotamia",
    "The Stone Age",
    "History of the Yangtze civilization",
    "History of the Yellow River civillization",
    "Asian history",
    "Chinese history",
    "Indian history",
    "Indonesian history",
    "Iranian history",
    "Australian history",
    "Ecclesiastical history of the Catholic Church",
    "Economic history",
    "Environmental history",
    "European history",
    "Intellectual history",
    "Jewish history",
    "Latin American history",
    "Modern history",
    "History of philosophy",
    "Ancient philosophy",
    "Contemporary philosophy",
    "Medieval philosophy",
    "Humanism",
    "Scholasticism",
    "Modern philosophy",
    "Political history",
    "Pre-Columbian era",
    "Russian history",
    "History of culture",
    "Scientific history",
    "Technological history",
    "World history",
    "Public history",
    "Physical geography",
    "Atmology",
    "Biogeography",
    "Climatology",
    "Coastal geography",
    "Emergency management",
    "Environmental geography",
    "Geobiology",
    "Geochemistry",
    "Geology",
    "Geomatics",
    "Geomorphology",
    "Geophysics",
    "Glaciology",
    "Hydrology",
    "Landscape ecology",
    "Lithology",
    "Meteorology",
    "Mineralogy",
    "Oceanography",
    "Palaeogeography",
    "Palaeontology",
    "Petrology",
    "Quaternary science",
    "Soil geography",
    "Human geography",
    "Behavioural geography",
    "Cognitive geography",
    "Cultural geography",
    "Development geography",
    "Economic geography",
    "Health geography",
    "Historical geography",
    "Language geography",
    "Marketing geography",
    "Military geography",
    "Political geography",
    "Population geography",
    "Religion geography",
    "Social geography",
    "Strategic geography",
    "Time geography",
    "Tourism geography",
    "Transport geography",
    "Urban geography",
    "Integrated geography",
    "Cartography",
    "Celestial cartography",
    "Planetary cartography",
    "Topography",
    "Acoustics",
    "Aerodynamics",
    "Applied physics",
    "Astrophysics",
    "Atomic, molecular, and optical physics",
    "Biophysics",
    "Computational physics",
    "Condensed matter physics",
    "Cryogenics",
    "Electricity",
    "Electromagnetism",
    "Elementary particle physics",
    "Experimental physics",
    "Fluid dynamics",
    "Geophysics",
    "Mathematical physics",
    "Mechanics",
    "Medical physics",
    "Molecular physics",
    "Newtonian dynamics",
    "Nuclear physics",
    "Optics",
    "Plasma physics",
    "Quantum physics",
    "Solid mechanics",
    "Solid state physics",
    "Statistical mechanics",
    "Theoretical physics",
    "Thermal physics",
    "Thermodynamics",
    "Logic in computer science",
    "Formal methods",
    "Logic programming",
    "Multi-valued logic",
    "Fuzzy logic",
    "Programming language semantics",
    "Type theory",
    "Algorithms",
    "Computational geometry",
    "Distributed algorithms",
    "Parallel algorithms",
    "Randomized algorithms",
    "Artificial intelligence",
    "Cognitive science",
    "Automated reasoning",
    "Computer vision",
    "Machine learning",
    "Artificial neural network",
    "Support vector machine",
    "Natural language processing",
    "Expert systems",
    "Robotics",
    "Data structures",
    "Computer architecture",
    "Computer graphics",
    "Image processing",
    "Scientific visualization",
    "Computer communications (networks)",
    "Cloud computing",
    "Information theory",
    "Internet, World Wide Web",
    "Ubiquitous computing",
    "Wireless computing",
    "Computer security and reliability",
    "Cryptography",
    "Fault-tolerant computing",
    "Computing in mathematics, natural sciences, engineering, and medicine",
    "Algebraic computation",
    "Computational biology",
    "Computational chemistry",
    "Computational mathematics",
    "Computational neuroscience",
    "Computational number theory",
    "Computational physics",
    "Computer-aided engineering",
    "Computational fluid dynamics",
    "Finite element analysis",
    "Numerical analysis",
    "Scientific computing",
    "Computing in social sciences, arts, humanities, and professions",
    "Community informatics",
    "Computational economics",
    "Computational finance",
    "Computational sociology",
    "Digital humanities",
    "History of computer hardware",
    "History of computer science",
    "Humanistic informatics",
    "Database",
    "Distributed database",
    "Object database",
    "Relational database",
    "Data management",
    "Data mining",
    "Information architecture",
    "Information management",
    "Information retrieval",
    "Knowledge management",
    "Multimedia, hypermedia",
    "Sound and music computing",
    "Distributed computing",
    "Grid computing",
    "Human-computer interaction",
    "Operating systems",
    "Parallel computing",
    "High-performance computing",
    "Programming languages",
    "Compilers",
    "Programming paradigms",
    "Concurrent programming",
    "Functional programming",
    "Imperative programming",
    "Logic programming",
    "Object-oriented programming",
    "Program semantics",
    "Type theory",
    "Quantum computing",
    "Software engineering",
    "Formal methods",
    "Theory of computation",
    "Automata theory",
    "Computability theory",
    "Computational complexity theory",
    "Concurrency theory",
    "VLSI design",
  ];

  for (let i = 0; i < 100; i++) {
    userIds.push(faker.random.uuid());
  }

  for (let i = 0; i < 100; i++) {
    const schedule = [];
    for (let w = 0; w < 7; w++) {
      const worksToday = faker.random.boolean();
      worksToday &&
        schedule.push({
          weekday: weekdays[w],
          from: faker.random.number({ min: 6, max: 12 }),
          to: faker.random.number({ min: 13, max: 18 }),
        });
    }

    const favoriteTeachersIds = userIds.filter(faker.random.boolean);

    const firstName = faker.name.firstName();
    const lastName = faker.name.lastName();

    data.users.push({
      id: userIds[i],
      firstName,
      lastName,
      email: faker.internet.email(firstName, lastName),
      password: "123456",
      avatarUrl: faker.random.image(),
      whatsapp: faker.phone.phoneNumber(),
      bio: faker.lorem.words(20),
      isTeacher: faker.random.boolean(),
      subject: subjects[Math.round(Math.random() * subjects.length)],
      perHourCost: faker.random.number({ min: 10, max: 1000, precision: 2 }),
      schedule,
      favoriteTeachersIds,
    });
  }
  return data;
};
